### PR TITLE
Configure whitesource.

### PR DESCRIPTION
**Pull request by dblock**
### Description

Not sure what happened in #1, I think it was closed because of a force push to main for the initial commit.
 
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by dbwiddis — COMMENTED** [review]
Recommend configuring this to use Remediate in preference to dependabot.

See https://github.com/opensearch-project/opensearch-ai-flow-framework/pull/1/files

```json
  "remediateSettings": {
    "workflowRules": {
      "enabled": true
    }
  }
```

**Comment by dblock** [comment]
I copied the contents of that .whitesource. Am I doing it right?

**Comment by dbwiddis** [comment]
Alternately it looks like for python there's another option: https://docs.safetycli.com/safety-2/

**Comment by dblock** [comment]
> Alternately it looks like for python there's another option: https://docs.safetycli.com/safety-2/

I'd rather not introduce new tools unless you feel very motivated ;)

**Comment by dbwiddis** [comment]
If you're happy with Renovate, let's merge this and close #5.

**Pull request merged**
